services:
  - type: web
    name: cdrp-api
    env: python
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: cdrp-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
    
  - type: pserv
    name: cdrp-db
    env: postgresql
    plan: free
    databaseName: cdrp_api
    user: cdrp_user